---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Generate WireGuard private key
  command: wg genkey
  register: wg_private_key_result
  changed_when: false

- name: Generate WireGuard public key
  shell: "echo '{{ wg_private_key_result.stdout }}' | wg pubkey"
  register: wg_public_key_result
  changed_when: false

- name: Set WireGuard facts
  set_fact:
    wg_private_key: "{{ wg_private_key_result.stdout }}"
    wg_public_key: "{{ wg_public_key_result.stdout }}"

- name: Configure WireGuard Interface
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  notify: Restart WireGuard

- name: Enable and start WireGuard
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started